services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    image: gogotex-frontend:local
    container_name: frontend
    hostname: frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - tex-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--spider", "http://localhost/" ]
      interval: 10s
      timeout: 3s
      retries: 5

networks:
  tex-network:
    external: true
