# Build stage for go-document
FROM golang:1.24-bullseye AS builder
WORKDIR /src
COPY . .
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN go mod download
RUN go build -o /gogotex-document ./cmd/document

# Final minimal image
FROM scratch
COPY --from=builder /gogotex-document /gogotex-document
ENV LOG_LEVEL=info
EXPOSE 5010
ENTRYPOINT ["/gogotex-document"]