services:
  gogotex-auth:
    image: gogotex-auth:local
    container_name: gogotex-auth
    hostname: gogotex-auth
    restart: unless-stopped

    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8081
      - KEYCLOAK_URL=http://keycloak-keycloak:8080/sso
      - KEYCLOAK_CLIENT_ID=gogotex-backend
      - MONGODB_URI=mongodb://mongodb-mongodb:27017
      - MONGODB_DATABASE=gogotex
      - DOC_SERVICE_INLINE=${DOC_SERVICE_INLINE:-false}

    # publish container port 8081 to host 5001 for local development (http://localhost:5001)
    ports:
      - "5001:8081"

    networks:
      - tex-network

networks:
  tex-network:
    external: true
