services:
  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb-exporter
    hostname: mongodb-exporter
    restart: always

    environment:
      - MONGODB_URI=mongodb://mongodb-mongodb:27017

    networks:
      - tex-network

networks:
  tex-network:
    external: true

