services:
  minio-minio:
    image: minio/minio:latest
    container_name: minio-minio
    hostname: minio-minio
    restart: unless-stopped

    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"

    volumes:
      - ./data:/data

    networks:
      - tex-network

    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  tex-network:
    external: true
